@host = http://localhost:5051

# Root: API info and available routes
GET {{host}}/
Accept: application/json

###

# Signature drinks
GET {{host}}/api/products
Accept: application/json

###

# Cities and maison counts
GET {{host}}/api/maisons
Accept: application/json

###
