// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheNoir.Api.Data;

#nullable disable

namespace TheNoir.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706060938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TheNoir.Api.Features.Maisons.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaisonCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "42 Vườn Trà",
                            Kind = "Flagship",
                            MaisonCount = 9,
                            Name = "Sài Gòn",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "18 Sương Mai",
                            Kind = "Salon",
                            MaisonCount = 5,
                            Name = "Hà Nội",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "27 Bến Lá",
                            Kind = "Riverside",
                            MaisonCount = 3,
                            Name = "Đà Nẵng",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "15 Đồi Mây",
                            Kind = "Garden house",
                            MaisonCount = 1,
                            Name = "Huế",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("TheNoir.Api.Features.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceVnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Milk Tea",
                            Description = "Our house black tea folded into silky fresh milk, finished with burnt-caramel pearls.",
                            ImageAlt = "A glass of milk tea with tapioca pearls on a dark table",
                            ImageUrl = "https://images.unsplash.com/photo-1558857563-b371033873b8?q=80&w=1200&auto=format&fit=crop",
                            Name = "Noir Signature",
                            PriceVnd = 65000,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pure Tea",
                            Description = "Hand-rolled oolong from estates at 1,200 m: orchid nose, honeyed finish, and steep after steep.",
                            ImageAlt = "Hot tea being poured from a teapot into a small cup",
                            ImageUrl = "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?q=80&w=1200&auto=format&fit=crop",
                            Name = "Highland Oolong",
                            PriceVnd = 58000,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Coffee",
                            Description = "Đà Lạt arabica dripped through a traditional phin, layered over condensed milk.",
                            ImageAlt = "A dark cup of Vietnamese coffee in moody light",
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1200&auto=format&fit=crop",
                            Name = "Phin Noir",
                            PriceVnd = 55000,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Matcha",
                            Description = "Stone-ground ceremonial matcha whisked over cold jasmine milk, grassy and bright.",
                            ImageAlt = "An iced green matcha drink in a tall glass",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=1200&auto=format&fit=crop",
                            Name = "Jade Cloud",
                            PriceVnd = 72000,
                            SortOrder = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
